// <auto-generated />
// This file was automatically generated by the PetePocoGenerator
// 
// The following connection settings were used to generate this file
// 
//     Connection String: `Server=DESKTOP-1K0UIDG\SQLEXPRESS; Database = EmployeeDB; Trusted_Connection=True;`
//     Provider:               `System.Data.SqlClient`

// <auto-generated />
namespace AspTask_EmployeeDirectory.Data
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    using PetaPoco;

    public partial class Record<T> where T : new()
    {
        private Dictionary<string, bool> modifiedColumns = null;
        [Ignore]
        public Dictionary<string, bool> ModifiedColumns { get { return modifiedColumns; } }
        protected void MarkColumnModified(string column_name)
        {
            if (ModifiedColumns != null)
            {
                ModifiedColumns[column_name] = true;
            }
        }

        private void OnLoaded()
        {
            modifiedColumns = new Dictionary<string,bool>();
        }
    }

    [TableName("[dbo].[Department]")]
    [PrimaryKey("DepartmentID")]
    [ExplicitColumns]
    public partial class Department
        : Record<Department>
    {
        [Column]
        public int DepartmentID
        {
            get { return _DepartmentID; }
            set
            {
                _DepartmentID = value;
                MarkColumnModified("DepartmentID");
            }
        }

        private int _DepartmentID;

        [Column]
        public string DepartmentName
        {
            get { return _DepartmentName; }
            set
            {
                _DepartmentName = value;
                MarkColumnModified("DepartmentName");
            }
        }

        private string _DepartmentName;

        [Column]
        public string DepartmentStatus
        {
            get { return _DepartmentStatus; }
            set
            {
                _DepartmentStatus = value;
                MarkColumnModified("DepartmentStatus");
            }
        }

        private string _DepartmentStatus;

    }

    [TableName("[dbo].[EmployeeDetails]")]
    [PrimaryKey("EmployeeID")]
    [ExplicitColumns]
    public partial class Employee
        : Record<Employee>
    {
        [Column]
        public int? DepartmentID
        {
            get { return _DepartmentID; }
            set
            {
                _DepartmentID = value;
                MarkColumnModified("DepartmentID");
            }
        }

        private int? _DepartmentID;

        [Column]
        public string Email
        {
            get { return _Email; }
            set
            {
                _Email = value;
                MarkColumnModified("Email");
            }
        }

        private string _Email;

        [Column]
        public int EmployeeID
        {
            get { return _EmployeeID; }
            set
            {
                _EmployeeID = value;
                MarkColumnModified("EmployeeID");
            }
        }

        private int _EmployeeID;

        [Column]
        public string EmployeeStatus
        {
            get { return _EmployeeStatus; }
            set
            {
                _EmployeeStatus = value;
                MarkColumnModified("EmployeeStatus");
            }
        }

        private string _EmployeeStatus;

        [Column]
        public string Firstname
        {
            get { return _Firstname; }
            set
            {
                _Firstname = value;
                MarkColumnModified("Firstname");
            }
        }

        private string _Firstname;

        [Column]
        public int? JobTitleID
        {
            get { return _JobTitleID; }
            set
            {
                _JobTitleID = value;
                MarkColumnModified("JobTitleID");
            }
        }

        private int? _JobTitleID;

        [Column]
        public string Lastname
        {
            get { return _Lastname; }
            set
            {
                _Lastname = value;
                MarkColumnModified("Lastname");
            }
        }

        private string _Lastname;

        [Column]
        public int? OfficeID
        {
            get { return _OfficeID; }
            set
            {
                _OfficeID = value;
                MarkColumnModified("OfficeID");
            }
        }

        private int? _OfficeID;

        [Column]
        public long? PhoneNumber
        {
            get { return _PhoneNumber; }
            set
            {
                _PhoneNumber = value;
                MarkColumnModified("PhoneNumber");
            }
        }

        private long? _PhoneNumber;

        [Column]
        public string PreferredName
        {
            get { return _PreferredName; }
            set
            {
                _PreferredName = value;
                MarkColumnModified("PreferredName");
            }
        }

        private string _PreferredName;

        [Column]
        public string SkypeID
        {
            get { return _SkypeID; }
            set
            {
                _SkypeID = value;
                MarkColumnModified("SkypeID");
            }
        }

        private string _SkypeID;

    }

    [TableName("[dbo].[JobTitle]")]
    [PrimaryKey("JobID")]
    [ExplicitColumns]
    public partial class JobTitle
        : Record<JobTitle>
    {
        [Column]
        public int JobID
        {
            get { return _JobID; }
            set
            {
                _JobID = value;
                MarkColumnModified("JobID");
            }
        }

        private int _JobID;

        [Column]
        public string JobName
        {
            get { return _JobName; }
            set
            {
                _JobName = value;
                MarkColumnModified("JobName");
            }
        }

        private string _JobName;

        [Column]
        public string JobStatus
        {
            get { return _JobStatus; }
            set
            {
                _JobStatus = value;
                MarkColumnModified("JobStatus");
            }
        }

        private string _JobStatus;

    }

    [TableName("[dbo].[Office]")]
    [PrimaryKey("OfficeID")]
    [ExplicitColumns]
    public partial class Office
        : Record<Office>
    {
        [Column]
        public int OfficeID
        {
            get { return _OfficeID; }
            set
            {
                _OfficeID = value;
                MarkColumnModified("OfficeID");
            }
        }

        private int _OfficeID;

        [Column]
        public string OfficeName
        {
            get { return _OfficeName; }
            set
            {
                _OfficeName = value;
                MarkColumnModified("OfficeName");
            }
        }

        private string _OfficeName;

        [Column]
        public string OfficeStatus
        {
            get { return _OfficeStatus; }
            set
            {
                _OfficeStatus = value;
                MarkColumnModified("OfficeStatus");
            }
        }

        private string _OfficeStatus;

    }

    [TableName("[dbo].[sysdiagrams]")]
    [PrimaryKey("diagram_id")]
    [ExplicitColumns]
    public partial class sysdiagram
        : Record<sysdiagram>
    {
        [Column]
        public byte[] definition
        {
            get { return _definition; }
            set
            {
                _definition = value;
                MarkColumnModified("definition");
            }
        }

        private byte[] _definition;

        [Column]
        public int diagram_id
        {
            get { return _diagram_id; }
            set
            {
                _diagram_id = value;
                MarkColumnModified("diagram_id");
            }
        }

        private int _diagram_id;

        [Column]
        public string name
        {
            get { return _name; }
            set
            {
                _name = value;
                MarkColumnModified("name");
            }
        }

        private string _name;

        [Column]
        public int principal_id
        {
            get { return _principal_id; }
            set
            {
                _principal_id = value;
                MarkColumnModified("principal_id");
            }
        }

        private int _principal_id;

        [Column]
        public int? version
        {
            get { return _version; }
            set
            {
                _version = value;
                MarkColumnModified("version");
            }
        }

        private int? _version;

    }

}

