// <auto-generated />
// This file was automatically generated by the PetePocoGenerator
//
// The following connection settings were used to generate this file
//
//     Connection String: `Server=DESKTOP-1K0UIDG\SQLEXPRESS; Database = EmployeeDB; Trusted_Connection=True;`
//     Provider:               `System.Data.SqlClient`

// <auto-generated />
namespace AspTask_EmployeeDirectory.Data
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    using PetaPoco;

    public partial class Record<T> where T : new()
    {
        private Dictionary<string, bool> modifiedColumns = null;
        [Ignore]
        public Dictionary<string, bool> ModifiedColumns { get { return modifiedColumns; } }
        protected void MarkColumnModified(string column_name)
        {
            if (ModifiedColumns != null)
            {
                ModifiedColumns[column_name] = true;
            }
        }

        private void OnLoaded()
        {
            modifiedColumns = new Dictionary<string, bool>();
        }
    }

    [TableName("[dbo].[EmployeeDetails]")]
    [ExplicitColumns]
    public partial class Employee
        : Record<Employee>
    {
        [Column]
        public string Department
        {
            get { return _Department; }
            set
            {
                _Department = value;
                MarkColumnModified("Department");
            }
        }

        private string _Department;

        [Column]
        public string Email
        {
            get { return _Email; }
            set
            {
                _Email = value;
                MarkColumnModified("Email");
            }
        }

        private string _Email;

        [Column]
        public int EmployeeID
        {
            get { return _EmployeeID; }
            set
            {
                _EmployeeID = value;
                MarkColumnModified("EmployeeID");
            }
        }

        private int _EmployeeID;

        [Column]
        public string Firstname
        {
            get { return _Firstname; }
            set
            {
                _Firstname = value;
                MarkColumnModified("Firstname");
            }
        }

        private string _Firstname;

        [Column]
        public string JobTitle
        {
            get { return _JobTitle; }
            set
            {
                _JobTitle = value;
                MarkColumnModified("JobTitle");
            }
        }

        private string _JobTitle;

        [Column]
        public string Lastname
        {
            get { return _Lastname; }
            set
            {
                _Lastname = value;
                MarkColumnModified("Lastname");
            }
        }

        private string _Lastname;

        [Column]
        public string Office
        {
            get { return _Office; }
            set
            {
                _Office = value;
                MarkColumnModified("Office");
            }
        }

        private string _Office;

        [Column]
        public long? PhoneNumber
        {
            get { return _PhoneNumber; }
            set
            {
                _PhoneNumber = value;
                MarkColumnModified("PhoneNumber");
            }
        }

        private long? _PhoneNumber;

        [Column]
        public string PreferredName
        {
            get { return _PreferredName; }
            set
            {
                _PreferredName = value;
                MarkColumnModified("PreferredName");
            }
        }

        private string _PreferredName;

        [Column]
        public string SkypeID
        {
            get { return _SkypeID; }
            set
            {
                _SkypeID = value;
                MarkColumnModified("SkypeID");
            }
        }

        private string _SkypeID;

    }

}
